import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap', // Ensures the font is displayed as soon as possible
  variable: '--font-poppins', // Assigns a CSS variable
  weight: ['400', '600', '700'], // Specify desired font weights
});



export const metadata = {
  title: "Bronto",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body
        className={`font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
